#!/bin/bash

if [ -z $SUDO_USER ]; then
  echo "Please run the script using sudo, e.g.,"
  echo ""
  echo "sudo ./increase_limits"
  exit 1
fi

echo
echo "Your current limits:"
launchctl limit | grep max
echo
echo "Would you like to set maxproc to 2048 and maxfiles to 196608?"
read -p "Are you sure? (y/n) " -n 1 -r

if [[ $REPLY =~ ^[Yy]$ ]]; then
  cp ./limit.maxfiles.plist /Library/LaunchDaemons/limit.maxfiles.plist
  chown root:wheel /Library/LaunchDaemons/limit.maxfiles.plist
  chmod 644 /Library/LaunchDaemons/limit.maxfiles.plist
  
  cp ./limit.maxproc.plist /Library/LaunchDaemons/limit.maxproc.plist
  chown root:wheel /Library/LaunchDaemons/limit.maxproc.plist
  chmod 644 /Library/LaunchDaemons/limit.maxproc.plist

  echo
  echo "New limits have been set. A reboot will be required for them to take effect."
else
  echo
  echo "Action aborted. No settings have been changed."
fi



