#!/bin/bash

port install pear-Console_Table
grep -q '/opt/local/lib/php/pear/bin' ~/.bash_profile || echo 'export PATH=$PATH:/opt/local/lib/php/pear/bin' >> ~/.bash_profile
grep -q 'PHP_PEAR_PHP_BIN' ~/.bash_profile || echo "alias pear='PHP_PEAR_PHP_BIN=/opt/local/bin/php pear'" >> ~/.bash_profile
PATH=$PATH:/opt/local/lib/php/pear/bin
export PHP_PEAR_PHP_BIN=/opt/local/bin/php

pear config-set php_bin /opt/local/bin/php
pear config-set php_dir /opt/local/lib/php/pear
pear config-set ext_dir /opt/local/lib/php54/extensions/no-debug-non-zts-20100525
pear config-set bin_dir /opt/local/bin
pear config-set cfg_dir /opt/local/lib/php/pear/cfg
pear config-set doc_dir /opt/local/lib/php/pear/docs
pear config-set www_dir /opt/local/lib/php/pear/www
pear config-set test_dir /opt/local/lib/php/pear/tests
pear config-set data_dir /opt/local/lib/php/pear/data
pear config-set auto_discover 1

pear channel-discover pear.drush.org
pear install drush/drush-5.9.0
